version: 2

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly

  groups:
    otel-contrib:
      patterns:
        - "opentelemetry-instrumentation-*"
      update-types:
        - minor
        - patch

    otel:
      patterns:
        - "opentelemetry-api"
        - "opentelemetry-sdk"
      update-types:
        - minor
        - patch

    misc:
      update-types:
        - minor
        - patch

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly