repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.8
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix", "--show-fixes"]
      # Run the formatter.
      - id: ruff-format
