# © 2023 SolarWinds Worldwide, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at:http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

# Build development environments (manylinux x86 or aarch, 64-bit)
# to locally build and publish solarwinds_apm Python APM library
services:
  x86_64:
    image: quay.io/pypa/manylinux_2_28_x86_64
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - ./:/code/solarwinds_apm
      - ../solarwinds-apm-liboboe/:/code/solarwinds-apm-liboboe
    working_dir: /code/solarwinds_apm
    entrypoint: ["/bin/bash", "-c"]
    command: 
    - |
       # boto3 for interaction with AWS
       # twine to upload to TestPyPi
       # tox for automated tests
       python3.8 -m pip install boto3 twine tox
       /bin/bash

  aarch64:
    image: quay.io/pypa/manylinux_2_28_aarch64
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - ALL
    volumes:
      - ./:/code/solarwinds_apm
      - ../solarwinds-apm-liboboe/:/code/solarwinds-apm-liboboe
    working_dir: /code/solarwinds_apm
    entrypoint: ["/bin/bash", "-c"]
    command: 
    - |
       # boto3 for interaction with AWS
       # twine to upload to TestPyPi
       # tox for automated tests
       python3.8 -m pip install boto3 twine tox
       /bin/bash
