AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SolarWinds Observability APM Lambda layer for Python
Parameters:
  LayerName:
    Type: String
    Description: Lambda layer name to be published
    Default: solarwinds-apm-python
Resources:
  SWOTelLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Ref LayerName
      Description: SolarWinds APM Python layer
      ContentUri: ./otel
      CompatibleRuntimes:
        - python3.8
        - python3.9
        - python3.10
        - python3.11
    Metadata:
      BuildMethod: makefile
  LambdaApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      OpenApiVersion: 3.0.2
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./function
      Description: Build SolarWinds APM Python Lambda layer and sample app from scratch
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/python/otel-instrument
      Tracing: Active
      Layers:
        - !Ref SWOTelLayer
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref LambdaApi
            Path: /
            Method: GET
