# © 2024 SolarWinds Worldwide, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at:http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

name: ReversingLabs scan

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true
        description: 'Artifact name earlier in the build. Should be zip file'
      package-name:
        type: string
        required: true
        description: 'RL package name on Portal'
      version:
        type: string
        required: true
        description: 'RL package version on Portal'
  

permissions:
  id-token: write
  contents: read
  statuses: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Scan artifact on the Portal
        id: rl-scan
        env:
          RLPORTAL_ACCESS_TOKEN: ${{ secrets.RLPORTAL_ACCESS_TOKEN }}
        uses: reversinglabs/gh-action-rl-scanner-cloud-only@v1
        with:
          artifact-to-scan: ${{ inputs.artifact-name }}
          rl-verbose: true
          rl-portal-server: solarwinds
          rl-portal-org: SolarWinds
          rl-portal-group: "SaaS-Agents-SWO"
          rl-package-url: solarwinds-apm-php/${{ inputs.package-name }}@${{ inputs.version }}
      - name: report the scan status
        if: success() || failure()
        run: |
          echo "The status is: '${{ steps.rl-scan.outputs.status }}'"
          echo "The description is: '${{ steps.rl-scan.outputs.description }}'"